"""LLM-like question generation fallback for offline environments.

This module provides deterministic generation and parameter pre-labeling.
If an external LLM is integrated later, keep this function signature stable.
"""

from random import choice
from app.engine.llm_client import (
    generate_mcq_with_llm,
    generate_question_with_llm,
    validate_generated_mcq_with_llm,
    cross_validate_with_gemini,
)
from app.services.question_format import (
    DEFAULT_GUESSING_C,
    normalize_format,
    normalize_format_fields,
    parse_matching_pairs,
)


def _predict_irt_params(stem: str, target_level: str) -> tuple[float, float, float]:
    """Heuristic pre-labeling for a/b/c before calibration by real responses."""
    length_factor = min(max(len(stem) / 120.0, 0.6), 1.6)
    if target_level == "Nhận biết":
        b = -0.8
        a = 1.1 * length_factor
        c = 0.25
    elif target_level == "Vận dụng":
        b = 1.0
        a = 1.5 * length_factor
        c = 0.2
    else:
        b = 0.2
        a = 1.3 * length_factor
        c = 0.2

    return round(a, 2), round(b, 2), round(c, 2)


def _clamp_irt(a: float, b: float, c: float) -> tuple[float, float, float]:
    a = min(max(float(a), 0.5), 2.5)
    b = min(max(float(b), -3.0), 3.0)
    c = min(max(float(c), 0.0), 0.35)
    return round(a, 2), round(b, 2), round(c, 2)


def _normalize_generated(payload: dict) -> dict:
    required = [
        "stem",
        "option_a",
        "option_b",
        "option_c",
        "option_d",
        "correct_answer",
        "difficulty_b",
        "discrimination_a",
        "guessing_c",
        "explanation",
    ]
    missing = [k for k in required if k not in payload]
    if missing:
        raise ValueError(f"Missing keys in generated payload: {missing}")

    correct_answer = str(payload["correct_answer"]).strip().upper()[:1]
    if correct_answer not in {"A", "B", "C", "D"}:
        raise ValueError("correct_answer must be one of A/B/C/D")

    a, b, c = _clamp_irt(
        payload["discrimination_a"],
        payload["difficulty_b"],
        payload["guessing_c"],
    )

    return {
        "stem": str(payload["stem"]).strip(),
        "question_format": "mcq",
        "option_a": str(payload["option_a"]).strip(),
        "option_b": str(payload["option_b"]).strip(),
        "option_c": str(payload["option_c"]).strip(),
        "option_d": str(payload["option_d"]).strip(),
        "correct_answer": correct_answer,
        "difficulty_b": b,
        "discrimination_a": a,
        "guessing_c": c,
        "explanation": str(payload["explanation"]).strip(),
    }


def _fallback_generate(topic_name: str, ctx: str, target_level: str, error: str | None = None) -> dict:
    stems = [
        f"Trong chủ đề '{topic_name}', phát biểu nào đúng nhất về: {ctx}?",
        f"Mệnh đề nào mô tả chính xác nhất kiến thức '{ctx}' trong {topic_name}?",
        f"Cho ngữ cảnh '{ctx}', lựa chọn nào là phù hợp nhất trong {topic_name}?",
    ]
    stem = choice(stems)

    option_a = "Khẳng định A"
    option_b = "Khẳng định B"
    option_c = "Khẳng định C"
    option_d = "Khẳng định D"
    correct = choice(["A", "B", "C", "D"])

    a, b, c = _predict_irt_params(stem, target_level)
    a, b, c = _clamp_irt(a, b, c)

    explanation = "Generated by fallback template generator; params are heuristic pre-labels."
    if error:
        explanation += f" Fallback reason: {error}"

    return {
        "stem": stem,
        "question_format": "mcq",
        "option_a": option_a,
        "option_b": option_b,
        "option_c": option_c,
        "option_d": option_d,
        "correct_answer": correct,
        "difficulty_b": b,
        "discrimination_a": a,
        "guessing_c": c,
        "explanation": explanation,
        "generation_source": "fallback",
        "llm_model": None,
    }


def _normalize_generated_for_format(fmt: str, payload: dict) -> dict:
    """Shape a non-MCQ LLM payload into the generated-draft contract.

    Format rules (options, key placement, default c) come from the shared
    normalizer so a draft matches exactly what the CRUD API would store.
    """
    stem = str(payload.get("stem", "") or "").strip()
    if not stem:
        raise ValueError("Missing stem in generated payload")

    fields = normalize_format_fields(fmt, payload)
    a, b, _ = _clamp_irt(
        payload.get("discrimination_a", 1.2) or 1.2,
        payload.get("difficulty_b", 0.0) or 0.0,
        0.0,
    )

    return {
        "stem": stem,
        "question_format": fmt,
        "option_a": fields["option_a"],
        "option_b": fields["option_b"],
        "option_c": fields["option_c"],
        "option_d": fields["option_d"],
        "correct_answer": fields["correct_answer"],
        "answer_text": fields["answer_text"],
        "matching_pairs": parse_matching_pairs(fields["matching_pairs"]),
        "difficulty_b": b,
        "discrimination_a": a,
        "guessing_c": fields["guessing_c"],
        "explanation": str(payload.get("explanation", "") or "").strip(),
    }


def _fallback_generate_for_format(
    fmt: str, topic_name: str, ctx: str, target_level: str, error: str | None = None
) -> dict:
    """Deterministic placeholder draft for non-MCQ formats when the LLM is unavailable."""
    a, b, _ = _predict_irt_params(topic_name, target_level)
    a, b, _ = _clamp_irt(a, b, 0.0)

    if fmt == "true_false":
        payload = {
            "stem": f"Phát biểu sau về '{ctx}' trong chủ đề {topic_name} là đúng.",
            "correct_answer": "A",
        }
    elif fmt == "short_answer":
        payload = {
            "stem": f"Hãy nêu khái niệm trung tâm của chủ đề '{topic_name}' liên quan tới {ctx}.",
            "answer_text": topic_name,
        }
    else:  # matching
        payload = {
            "stem": f"Ghép mỗi khái niệm trong chủ đề '{topic_name}' với mô tả tương ứng.",
            "pairs": [
                {"left": "Khái niệm 1", "right": "Mô tả 1"},
                {"left": "Khái niệm 2", "right": "Mô tả 2"},
                {"left": "Khái niệm 3", "right": "Mô tả 3"},
            ],
        }

    explanation = "Generated by fallback template generator; params are heuristic pre-labels."
    if error:
        explanation += f" Fallback reason: {error}"

    payload.update(
        {
            "difficulty_b": b,
            "discrimination_a": a,
            "guessing_c": DEFAULT_GUESSING_C[fmt],
            "explanation": explanation,
        }
    )
    draft = _normalize_generated_for_format(fmt, payload)
    draft["generation_source"] = "fallback"
    draft["llm_model"] = None
    return draft


def generate_question_from_topic(
    topic_name: str,
    knowledge_context: str | None,
    target_level: str,
    runtime_settings: dict | None = None,
    question_format: str = "mcq",
) -> dict:
    """Generate a question draft of any supported format.

    Uses the LLM when enabled, otherwise a fallback template generator so the
    endpoint keeps working offline.
    """
    ctx = knowledge_context.strip() if knowledge_context else topic_name

    if runtime_settings is None:
        raise ValueError("runtime_settings is required")

    fmt = normalize_format(question_format)
    llm_enabled = bool(runtime_settings.get("llm_enabled"))
    llm_model = runtime_settings.get("llm_model")

    if fmt != "mcq":
        if not llm_enabled:
            return _fallback_generate_for_format(fmt, topic_name, ctx, target_level)
        try:
            llm_payload = generate_question_with_llm(
                topic_name=topic_name,
                knowledge_context=ctx,
                target_level=target_level,
                question_format=fmt,
                runtime_settings=runtime_settings,
            )
            normalized = _normalize_generated_for_format(fmt, llm_payload)
            normalized["generation_source"] = "llm"
            normalized["llm_model"] = llm_model
            return normalized
        except Exception as exc:
            return _fallback_generate_for_format(fmt, topic_name, ctx, target_level, error=str(exc))

    if llm_enabled:
        try:
            llm_payload = generate_mcq_with_llm(
                topic_name=topic_name,
                knowledge_context=ctx,
                target_level=target_level,
                runtime_settings=runtime_settings,
            )
            normalized = _normalize_generated(llm_payload)
            normalized["generation_source"] = "llm"
            normalized["llm_model"] = llm_model
            return normalized
        except Exception as exc:
            return _fallback_generate(topic_name, ctx, target_level, error=str(exc))

    return _fallback_generate(topic_name, ctx, target_level)


def generate_validated_question_for_cat(
    topic_name: str,
    knowledge_context: str,
    target_level: str,
    target_b: float,
    target_a: float,
    target_c: float,
    max_attempts: int = 2,
    runtime_settings: dict | None = None,
) -> dict:
    """Generate a CAT question with target IRT and self-validation.

    Acceptance criteria:
    - validation is_valid is True
    - solved answer matches generated correct_answer
    - estimated_b is close enough to target_b
    """
    if runtime_settings is None:
        raise ValueError("runtime_settings is required")

    llm_enabled = bool(runtime_settings.get("llm_enabled"))
    llm_model = runtime_settings.get("llm_model")

    if not llm_enabled:
        return _fallback_generate(topic_name, knowledge_context, target_level, error="LLM disabled")

    last_error = "unknown"
    for _ in range(max(1, max_attempts)):
        try:
            raw = generate_mcq_with_llm(
                topic_name=topic_name,
                knowledge_context=knowledge_context,
                target_level=target_level,
                target_b=target_b,
                target_a=target_a,
                target_c=target_c,
                runtime_settings=runtime_settings,
            )
            normalized = _normalize_generated(raw)
            validation = validate_generated_mcq_with_llm(
                normalized,
                target_b=target_b,
                runtime_settings=runtime_settings,
            )

            if not validation["is_valid"]:
                raise ValueError(f"validation rejected: {validation['notes']}")
            if validation["solved_answer"] != normalized["correct_answer"]:
                raise ValueError("validator solved answer mismatches generated key")
            if abs(float(validation["estimated_b"]) - float(target_b)) > 0.8:
                raise ValueError("validator estimated_b too far from target")

            # Optional second gate: Gemini must not disagree with the key
            gemini = cross_validate_with_gemini(normalized, runtime_settings=runtime_settings)
            if gemini["enabled"] and gemini["agree"] is False:
                raise ValueError(f"gemini disagrees: {gemini['notes']}")
            if gemini["enabled"]:
                normalized["explanation"] += f" | Gemini cross-check: {'đồng thuận' if gemini['agree'] else 'không kết luận'}."

            normalized["generation_source"] = "llm-cat"
            normalized["llm_model"] = llm_model
            normalized["explanation"] = (
                normalized["explanation"]
                + f" | Self-check: est_b={validation['estimated_b']}, conf={validation['confidence']:.2f}."
            )
            return normalized
        except Exception as exc:
            last_error = str(exc)

    return _fallback_generate(topic_name, knowledge_context, target_level, error=f"cat-validation-failed: {last_error}")
